name: Go
on:
  push:
    branches:
    - master
    - develop
    - ci
  pull_request:
    branches:
    - master
    - develop
    - ci
jobs:

  build:
    name: Build .deb package for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, i386, mipsel, mips, armhf, arm64]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: sh contrib/deb/generate.sh
      env:
        PKGARCH: ${{ matrix.platform }}
        CINAME: yggdrasil
        CIVERSION: 0.3.8
